apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    envFrom:        # Updated by adding this section to use Secrets yaml File.
    - secretRef:
        name: db-secret
