apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness
spec:
  containers:
  - name: nginx
    image: nginx
    livenessProbe:
      httpGet:
        path: /test.html        # Updated from   /    ==>   /test.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3