apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app
spec:
  containers:
  - name: nodejs
    image: node
    command: ["node", "-e", "require('http').createServer((req, res) => res.end('OK')).listen(8080)"]
    readinessProbe:       # Added readinessProbe to this file to check HTTP endpoint.
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10

